-- ForceQA — ordem de execução no SQL Editor do Supabase
--
-- 1. schema.sql                         (base: tabelas, RLS inicial)
-- 2. migration_auth_profile_trigger.sql (perfil em public.users no signup)
-- 3. migration_projects.sql
-- 4. migration_boards.sql
-- 5. migration_board_views.sql
-- 6. migration_kanban_columns.sql
-- 7. migration_bug_types.sql
-- 8. migration_access_and_security.sql  (membership, evidências Storage, role lock)
-- 9. migration_room_access_ui.sql       (acesso só via UI; guest ainda entra pelo ID)
-- 10. migration_organizations.sql       (org padrão; ainda sem isolamento entre tenants)
-- 11. migration_organization_scope.sql  (RLS e admin presos à org; superadmin atravessa)
-- 12. migration_create_organization_admin.sql (criar org + admin sem o Auth mascarar erro)
-- 13. migration_room_organization_from_creator.sql (sala/projeto herda a org de quem criou)
-- 14. migration_security_hardening.sql  (RLS privilegiada, guest, storage, comentários)
-- 15. migration_session_ops.sql         (anexos, duplicata, checklist, webhook da org)
-- 16. migration_export_api.sql          (token SHA-256 para GET /api/export/*)
--
-- Em ambiente já existente, rode apenas as migrations ainda não aplicadas.
-- A migration_access_and_security.sql é obrigatória para convites, join e RLS de viewer.
-- A migration_room_access_ui.sql é obrigatória para o painel de membros e checkboxes em Usuários.
-- A migration_organizations.sql é obrigatória antes do app gravar organization_id.
-- A migration_organization_scope.sql isola leitura/escrita por org (rode depois da 10).
-- A migration_create_organization_admin.sql é obrigatória para a tela Organizações criar o primeiro admin.
-- A migration_room_organization_from_creator.sql evita 403 ao criar sala/projeto numa org que não é a padrão.
-- A migration_security_hardening.sql é obrigatória: trava is_superadmin/org, guest sem hop de tenant, bucket privado.
-- A migration_session_ops.sql é obrigatória para vários anexos, duplicata, checklist e webhook.
-- A migration_export_api.sql é obrigatória para a API de extração (GitLab puxar cards).
-- Se o SQL Editor retornar deadlock (40P01), espere uns segundos e rode o arquivo de novo.
